SOUND_HEAD_NAME: "sid"
IMAGE_HEAD_NAME: "img"
SMALL: "_s"
SOUND_DATA_SIZE: 15
IMAGE_DATA_SIZE: 6
SHOW_IMAGE_SIZE: 200
INDEX_IMAGE_SIZE: 80
NEW_SOUND_VALUE: "アップロードするファイルを選択してください。"
NEW_THUMB_VALUE: "サムネイルを選択してください。"
EDIT_SOUND_VALUE: "ファイルを変更する場合は選択してください。"
EDIT_THUMB_VALUE: "サムネイルを変更する場合は選択してください。"
NORMAL_IMAGE_SIZE: 500
SMALL_IMAGE_SIZE: 200